name: Release to PyPI

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    environment: release
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build and package
        run: |
          pip install wheel
          python setup.py sdist bdist_wheel

      - name: Publish to PyPI
        run: |
          pip install twine
          twine upload --config-file .pypirc dist/* --verbose
